### ISSUE TITLE
Unable to edit record dates

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#27] opened 2021-04-20 14:31 UTC
We've been asked to amend a couple of record dates but the changes won't save. We could do this previously I think so have permissions changed?
![image](https://user-images.githubusercontent.com/80914584/115413806-67756500-a1ed-11eb-9539-ba3ba082d6f0.png)

**Comment by johnvanbreda** [comment] 2021-04-27 12:34
@davidnicholls125 I managed to amend the date on a test record. Please let me know what steps you are taking, plus an example record ID and the date you want to change it to.

**Comment by davidnicholls125** [comment] 2021-04-27 12:44
I brought up the record on the verification page and went to 'edit'.
The date changed on the form OK but when I submitted it I was returned to the home page with the message below.
![image](https://user-images.githubusercontent.com/80914584/116243145-867c7580-a75e-11eb-9bee-20d82890ca68.png)
![image](https://user-images.githubusercontent.com/80914584/116243211-9e53f980-a75e-11eb-8508-9b9e9b74d257.png)

**Comment by johnvanbreda** [comment] 2021-04-28 13:04
Should be fixed now - there was a validation error caused by the form not being correctly configured for lat/long data from the app.

**Closed as completed by johnvanbreda** 2021-04-28 13:04 UTC
Labels: Problem priority 2, Priority 1
