### ISSUE TITLE
Editing records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#114] opened 2022-09-13 07:36 UTC
The sex and attribute fields are not appearing as editable entries when bringing up the edit page for a record. Can this be fixed please?
![image](https://user-images.githubusercontent.com/80914584/189839692-23855beb-1c61-4f1c-989b-1844d76fc652.png)

**Comment by johnvanbreda** [comment] 2022-09-13 15:45
Fixed - a small bug caused by the photo row.

**Comment by davidnicholls125** [comment] 2022-09-13 16:21
It's still not displaying the sex and attribute fields on the record edit page. I've checked a few of my moth records, one displayed the sex field but all the others are blank on both sex and attribute.

**Comment by johnvanbreda** [comment] 2022-09-14 09:14
The attribute column was a different problem due to the column title being overridden from Stage - now fixed.

**Closed as completed by johnvanbreda** 2022-09-14 09:14 UTC
