### ISSUE TITLE
Wild Place maps

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#96] opened 2022-02-13 17:55 UTC
We are again working with the County Council on their verge biodiversity project and are setting up Wild Place pages for each participating verge. However I've noticed that the map boundary outline for Cropston, Leicester Road is mis-aligned with the base map - see below. In Indicia the map looks fine and seems accurate. Can this be fixed?
Also, when the page loads, the map needs to be zoomed in further. Is the degree of zoom custom to the size of the site or a one-size fits all? Is this anything I can adjust?
Also on the Wild Place/Parish pages, we have lost the links to the species pages on both the records and images - can these be reinstated please?
![image](https://user-images.githubusercontent.com/80914584/153767998-3f413595-bcdd-4289-b8b9-a1eb46325722.png)

**Comment by johnvanbreda** [comment] 2022-02-15 17:09
There seems to be a problem with the slight 3D alignment that the Google Hybrid layer shows when zooming close in around this site. If I use the submit records form to add a square on top of the curve by the junction of Latimer Road whilst zoomed a couple of levels out, then zoom in, you can see that the map changes aspect slightly and the square moves off the curved junction edge. I cannot reproduce this in iRecord which uses a combination of Open Street Map and Google Satellite. I also cannot reproduce this in other parts of the UK.

I also notice that the hybrid layer has a shading drawn for the road which is also out of alignment.

One suggested approach would be to switch to the Open Street Map / Google Hybrid layer combination as used on iRecord. It changes the appearance of zoomed out maps but they might be considered tidier anyway. I'll look at the initial zoom once we've worked out the positioning problem.

**Comment by davidnicholls125** [comment] 2022-04-04 13:21
Not sure whether you are waiting on me for this one. By all means try the hybrid approach if you think it will help. On iRecord it appears that the view switches to satellite when you have zoomed to a certain level, if this is the case is there any difference as it is the zoomed in view that is misaligned? It would be good to resolve it, particular for small sites such as the verges where the misalignment is confusing.

**Comment by johnvanbreda** [comment] 2022-04-05 13:32
@davidnicholls125 now fixed. It was quite a tricky thing to get to the bottom of, relating to turning off the "tilt" function of a Google layer and also delaying zooming to the polygon until after the base layer is fully loaded.

**Closed as completed by johnvanbreda** 2022-04-05 13:32 UTC
Labels: Priority 1
