### ISSUE TITLE
new Wild Place error

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#92] opened 2022-01-27 16:01 UTC
I've just tried to set up a new Wild Place page from a kmz file sent to me. I converted it to a shp zip file as usual and loaded it into Indicia which seemed fine. However the Drupal page is giving an error. What needs amending?
https://www.naturespot.org.uk/Lady_Hay_Wood

**Comment by johnvanbreda** [comment] 2022-01-28 20:18
Duplicate of #93 - now fixed

**Closed as completed by johnvanbreda** 2022-01-28 20:18 UTC
Labels: Priority 1
